# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Aakash Bansal"                                # Your name
  description: "A Financial Engineering student"   # A brief slogan (optional)
  image: img/img.jpeg
  
  favicon: img/original_output.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/original_output.png
    
    # your sub-pages
    left:
      - text: "Education"
        href: Education/index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Interests"
        href: photography/index.qmd
      - text: "CV"
        href: cv/index.qmd

    
    # your social media handles
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/aakashban/
      - icon: envelope
        aria-label: email
        href: "mailto:aakashb4@illinois.edu"  
  
  


project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute: 
  freeze: true

format:
  html: 
    fontsize: 1.1em
    theme: lux
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true